# CTAB to JSON

Taking gtmseg.ctab (FreeSurfer's expanded color table) and converting it to JSON dictionary.

In [2]:
import pandas as pd
import json
import numpy as np

In [4]:
fields = ['region_index','name','color_r','color_g','color_b','alpha','tissue_type']
ctab = pd.read_csv('gtmseg.ctab',sep='\s+',comment='#',names=fields)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_2763999/441283904.py:2: SyntaxWarning: invalid escape sequence '\s'
  ctab = pd.read_csv('gtmseg.ctab',sep='\s+',comment='#',names=fields)

In [5]:
ctab

,region_index,name,color_r,color_g,color_b,alpha,tissue_type
0,0,Unknown,0,0,0,0,0
1,1,Left-Cerebral-Exterior,70,130,180,0,5
2,2,Left-Cerebral-White-Matter,245,245,245,0,3
3,4,Left-Lateral-Ventricle,120,18,134,0,4
4,5,Left-Inf-Lat-Vent,196,58,250,0,4
...,...,...,...,...,...,...,...
106,2031,ctx-rh-supramarginal,80,160,20,0,1
107,2032,ctx-rh-frontalpole,100,0,100,0,1
108,2033,ctx-rh-temporalpole,70,20,170,0,1
109,2034,ctx-rh-transversetemporal,150,150,200,0,1
110,2035,ctx-rh-insula,255,192,32,0,1

In [14]:
ctab_json = ctab[['region_index','name']]

In [15]:
ctab_json

     region_index                        name
0               0                     Unknown
1               1      Left-Cerebral-Exterior
2               2  Left-Cerebral-White-Matter
3               4      Left-Lateral-Ventricle
4               5           Left-Inf-Lat-Vent
..            ...                         ...
106          2031        ctx-rh-supramarginal
107          2032          ctx-rh-frontalpole
108          2033         ctx-rh-temporalpole
109          2034   ctx-rh-transversetemporal
110          2035               ctx-rh-insula

[111 rows x 2 columns]

In [18]:
ctab_json.to_json('gtmseg_ctab.json',index=False,orient='split',indent=4)

In [19]:
new_ctab = pd.read_json('gtmseg_ctab.json',orient='split')

In [20]:
new_ctab==ctab_json

     region_index  name
0            True  True
1            True  True
2            True  True
3            True  True
4            True  True
..            ...   ...
106          True  True
107          True  True
108          True  True
109          True  True
110          True  True

[111 rows x 2 columns]

In [21]:
new_ctab

     region_index                        name
0               0                     Unknown
1               1      Left-Cerebral-Exterior
2               2  Left-Cerebral-White-Matter
3               4      Left-Lateral-Ventricle
4               5           Left-Inf-Lat-Vent
..            ...                         ...
106          2031        ctx-rh-supramarginal
107          2032          ctx-rh-frontalpole
108          2033         ctx-rh-temporalpole
109          2034   ctx-rh-transversetemporal
110          2035               ctx-rh-insula

[111 rows x 2 columns]